type EventName =
  | "app_opened"
  | "sign_in_completed"
  | "guest_mode_started"
  | "onboarding_completed"
  | "create_started"
  | "photo_selected"
  | "audio_selected"
  | "preview_viewed"
  | "video_export_started"
  | "video_exported"
  | "video_export_failed"
  | "video_saved_to_camera_roll"
  | "share_tapped_instagram"
  | "share_tapped_tiktok"
  | "project_reopened"
  | "project_actions_opened"
  | "project_delete_started"
  | "project_deleted"
  | "project_edit_started"
  | "project_autosave_succeeded"
  | "project_autosave_failed"
  | "project_media_replaced"
  | "project_title_edit_opened"
  | "project_title_updated"
  | "notification_received"
  | "notification_tapped"
  | "project_create_failed_during_export"
  | "profile_preference_updated"
  | "account_delete_started"
  | "account_deleted"
  | "sign_out_tapped"
  | "sign_out_completed";

export type { EventName };
