import { StyleSheet } from "react-native";
import { colors, radius, spacing, typography } from "@/constants/tokens";

export const backgroundControlStyles = StyleSheet.create({
  controlSection: {
    gap: spacing.sm,
  },
  controlHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  controlLabel: {
    ...typography.caption,
    color: colors.dark.textSecondary,
    fontWeight: "600",
    textTransform: "none",
    letterSpacing: 0.16,
  },
  controlHint: {
    ...typography.caption,
    color: colors.dark.textSecondary,
    marginTop: spacing.xs,
    textAlign: "center",
  },
  backgroundRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "center",
    gap: spacing.sm,
    paddingRight: spacing.sm,
  },
  backgroundSwatchWrap: {
    width: 38,
    height: 38,
    borderRadius: radius.md,
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  backgroundSwatchWrapSelected: {
    borderWidth: 2,
    borderColor: colors.accent.primary,
    shadowColor: colors.accent.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 8,
  },
  backgroundSwatch: {
    width: "100%",
    height: "100%",
    borderRadius: radius.md,
  },
  backgroundSwatchWithChild: {
    alignItems: "center",
    justifyContent: "center",
  },
  customBackgroundToggleWrap: {
    borderWidth: 0,
    borderColor: "transparent",
  },
  customBackgroundToggleIcon: {
    position: "absolute",
  },
  customColorCard: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.03)",
    padding: spacing.sm,
    gap: spacing.sm,
  },
  customColorHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  customColorTitle: {
    ...typography.caption,
    color: colors.dark.text,
    fontWeight: "700",
  },
  customColorSwatch: {
    width: 16,
    height: 16,
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
  },
  customHueHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: spacing.sm,
  },
  customHueLabel: {
    ...typography.caption,
    color: colors.dark.textSecondary,
    fontWeight: "600",
    textTransform: "none",
    letterSpacing: 0.16,
  },
  paletteStripScroll: {
    marginHorizontal: -spacing.xs,
  },
  paletteStripWrap: {
    gap: spacing.xs,
  },
  paletteStripRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  paletteSection: {
    gap: spacing.xs,
  },
  paletteSectionLabel: {
    ...typography.caption,
    color: colors.dark.textSecondary,
    fontWeight: "600",
    fontSize: 11,
    letterSpacing: 0.14,
    textTransform: "none",
    paddingHorizontal: spacing.xs,
  },
  paletteSectionSwatches: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  paletteSectionDivider: {
    marginTop: spacing.xs,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.08)",
    marginHorizontal: spacing.xs,
  },
  paletteDotWrap: {
    width: 38,
    height: 38,
    borderRadius: radius.md,
    borderWidth: 0,
    borderColor: "transparent",
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  paletteDotWrapSelected: {
    borderWidth: 2,
    borderColor: colors.accent.primary,
    shadowColor: colors.accent.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 8,
  },
  paletteDotWrapDisabled: {
    opacity: 0.42,
  },
  palettePager: {
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "center",
    gap: spacing.xs,
    paddingTop: 2,
  },
  palettePagerDot: {
    width: 6,
    height: 6,
    borderRadius: radius.full,
    backgroundColor: "rgba(255,255,255,0.24)",
  },
  palettePagerDotActive: {
    width: 16,
    backgroundColor: colors.accent.primary,
  },
  customToneRow: {
    flexDirection: "row",
    flexWrap: "nowrap",
    alignItems: "center",
    gap: spacing.sm,
    paddingRight: spacing.sm,
  },
  customToneSwatchWrap: {
    width: 38,
    height: 38,
    borderRadius: radius.md,
    borderWidth: 0,
    borderColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  customToneSwatchWrapSelected: {
    borderWidth: 2,
    borderColor: colors.accent.primary,
    shadowColor: colors.accent.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 8,
  },
  optionPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: radius.full,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.dark.border,
  },
  optionPillPressed: {
    opacity: 0.85,
  },
  optionPillText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.dark.text,
  },
});
