/** Mirrors design handoff + docs/design-assets/onboarding-workflow/copy.md */
export const onboardingCopy = {
  loading: "Preparing your workspace…",
  skip: "Skip",
  progressOf: "of",
  notNow: "Not now",
  continue: "Continue",
  skipProfile: "Skip for now",
  openingApp: "Opening MusicPromo…",
  alreadyGranted: "You're all set",

  value: {
    eyebrow: "Fast start",
    title: "Turn one photo and one track into a promo in seconds",
    body: "Drop in a photo, add an audio clip, and MusicPromo builds a vertical promo video. No editor to fight.",
    cta: "Get started",
    posterTag: "9:16",
    posterName: "Your name",
  },
  flow: {
    eyebrow: "Simple flow",
    title: "Three steps, then you're done",
    cta: "Continue",
    rows: [
      { title: "Pick a photo", body: "Choose any shot from your library." },
      { title: "Pick a track", body: "Add an audio clip and trim the loop." },
      { title: "Share it", body: "Post it, or save to your Camera Roll." },
    ] as const,
  },
  permPhotos: {
    eyebrow: "Photo access",
    title: "Allow access to your photos",
    body: "MusicPromo opens your library so you can pick the image for your promo. You choose what to use.",
    bullet: "You choose every file",
    note: "Nothing leaves your phone until you share. You can change this later in Settings.",
    cta: "Allow photo access",
  },
  permAudio: {
    eyebrow: "Audio access",
    title: "Allow access to your audio",
    body: "Pick a track from your music library and trim it to the perfect loop.",
    bullet: "You choose every file",
    note: "We only read the clip you choose. You can change this later in Settings.",
    cta: "Allow audio access",
  },
  permSave: {
    title: "Save to your camera roll",
    body: "MusicPromo saves exported videos to your camera roll so you can share them.",
    bullet: "You control when exports are saved",
  },
  profileSetup: {
    title: "Set up your artist card",
    subtitle: "This shows on every promo you share. You can change it later.",
    guestHelper: "Sign in to link an existing Music Promo.",
    artistNameLabel: "Artist name",
    artistNameRequired: "Required",
    artistNamePlaceholder: "e.g. Midnight Drive",
    bioLabel: "Bio",
    bioPlaceholder: "What's your sound? A line or two about you.",
    addBanner: "Add banner",
    changeBanner: "Change banner",
    addPhoto: "Add photo",
    changePhoto: "Change photo",
    previewLabel: "Preview",
    emptyPromos: "Your promos will show here",
    cta: "Continue",
    saveError: "Couldn't save your profile. Try again.",
  },
  ready: {
    eyebrow: "You are set",
    title: "You're ready to make your first promo",
    body: "Tap the plus on Home anytime to start. Your first promo takes about a minute.",
    cta: "Make my first promo",
  },
} as const;

export const BIO_MAX_LENGTH = 280;
